# Answers to Exercises

**Exercise**: Let's say you want the sum of the 3rd and 4th element of v. Write a line of code that does just that.

In [ ]:
summed = v[3:].sum()

**Exercise:** What if you wanted the 2x2 matrix in the middle of A? Uncomment the code below (click in the box so you have a flashing cursor, and delete the #), erase the underscore blanks, and fill in the correct numbers.

In [ ]:
matrix_in_the_middle = random[1:3, 1:3]

**Exercise**: Find the numbers who are less than the mean of all the elements of the matrix? Uncomment out the following (erase the #) and fill in the blank between the brackets.

In [ ]:
random_matrix[random_matrix > random_matrix.mean()]

### Broadcasting

In [56]:
x = np.array([1, 2])
y = np.array([[3], [4]])
x + y # what does this output

array([[4, 5],
       [5, 6]])

### Linear Algebra

In [57]:
x = np.arange(1000).reshape(1000, 1)
b = np.ones((1000, 1))
X = np.append(x, b, axis=1)

Y = 2 * np.arange(1000).reshape(1000, 1) + 4 + np.random.random()

In [58]:
theta_hat = np.linalg.solve(np.dot(X.T, X), np.dot(X.T, Y))
theta_hat

array([[ 2.        ],
       [ 4.41398437]])

In [59]:
loss = np.dot((Y - np.dot(X, theta_hat)).T, (Y - np.dot(X, theta_hat)))
loss

array([[  8.10227167e-19]])

### Pandas

In [120]:
fare = titanic_train[titanic_train['Sex'] == 'female']['Fare'].sum()

13966.6628