# Numpy and Pandas
---

@author = Ajay Raj and Roland Chin

An informal introduction to your least-worst enemy in the realm of data science. Numpy is an optimized math library for Python. Most of the optimization occurs in C, and some neat Python backend tinkering allows us to interface with it in Python. The code is vectorized as much as possible, which means that there's a heavy focus on using arrays (treated as n-dimensional vectors) to do operations. This is a shift away from doing looped operations.

For example:
If you wanted to compute the dot product of two arrays [1, 2, 3, 4, 5] and [5, 4, 3, 2, 1], you could either loop through the arrays

```python
sum = 0
for v1, v2 in zip(arr1, arr2):
    sum += v1*v2
```

Or, you could perform all the multiplications at once, and then add them together. That's basically what Numpy does behind the scenes. So doing the dot product in numpy is very simple:

```python

arr1 = np.array(arr1) # casting lists to np arrays
arr2 = np.array(arr2)
dp = arr1.dot(arr2)
```

## Table of Contents

We will be going over the following:

* **basic operations**

* **array indexing**

* **broadcasting**

* **linear algebra**

* **conditions**

* **table manipulation**

Before we begin, vectors are single dimensional matrices, and a matrix is multidimensional. In Numpy, we represent both with np.arrays. We can also use np.matrix, but arrays are faster performance wise, and matrices are less easily manipulated and are inherently 2 dimensional.

## Basic Operations

In [1]:
import numpy as np

NumPy is a Python library that is used to handle linear algebra operations. It does a couple amazing things under the hood that make certain operations lightning fast, and makes large scale data processing possible (like Pandas –– covered later).

NumPy holds data in **arrays**.

In [2]:
v = np.array([1, 2, 3, 4, 5]) #creating an array
v

array([1, 2, 3, 4, 5])

You can **index** an element of an array by putting it's index number in brackets after the name of the array.

Note: the index of arrays start with **0**, as opposed to 1 as in R.

In [3]:
v[2]

3

In [4]:
v[5] #why does this error?

IndexError: index 5 is out of bounds for axis 0 with size 5

**Exercise**: Let's say you want the sum of the 3rd and 4th element of v. Click the box in the following cell so you see a flashing cursor, delete the #'s, and write a line of code that does just that.

In [5]:
summed = ###
summed

SyntaxError: invalid syntax (<ipython-input-5-5655bbe3078f>, line 1)

### Indexing 2-D Arrays in Numpy

What is a 2-D array? It's an array of arrays. Also referred to as a matrix. 

This is what a 2D list looks like in vanilla Python.
```python
A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    ]
```

Accessing the number 5 is not too easy however. There are no built-in routines to help you index 2 layers deep into a list. So you have to index into multiple arrays one at a time:

```python
# getting the number 5 from A
# A[1] = [4, 5, 6]
# A[1][1] = 5
five = A[1][1]
```

When you store an array as an np.array, you are not only gaining a runtime speedup, you're also getting a speedup in writing your code because you now have advanced indexing! 

Now, we'll show how to index in a similar 4x4 array in numpy's array format.

The function ```randn ``` creates a sample from the standard normal distribution (the bell shaped curve with a mean 0 and variance 1).

In [6]:
random = np.random.randn(3,4) #the 1st argument is the number of rows, the 2nd argument is the number of columns
random

array([[-0.65966542, -0.91487335,  0.48674521, -0.55549324],
       [-0.55342113,  0.27323083, -0.31769338, -1.86863277],
       [-1.43459456,  1.40393366, -0.21011679,  0.76348473]])

Let's multiply all its values by 10 so it's more easier to read.

In [7]:
bigger_random = random * 10
bigger_random

array([[ -6.59665415,  -9.14873346,   4.86745208,  -5.55493244],
       [ -5.53421125,   2.73230826,  -3.17693378, -18.68632775],
       [-14.34594559,  14.03933658,  -2.10116786,   7.63484729]])

That's better, but there's still a lot of decimals. Let's go 1 step further and round all the values with the astype function, which casts it's arguments to a specified type. Here it'll round all the values in the array to the nearest integer.

In [47]:
A = bigger_random.astype(int)
A

array([[ -6,  -9,   4,  -5],
       [ -5,   2,  -3, -18],
       [-14,  14,  -2,   7]])

Now let's select certain values.

In [48]:
A[2, 2] # the element in row index 2, column index 2

-2

You can also use a colon ```[start:end]``` to select multiple elements. For example:

```[1:5]``` is equivalent to "from element index 1 to 4" (Python doesn't include the last index)

```[1:]``` is equivalent to "from element index 1 to all the way to the end"

```[0:]``` is equivalent to ```[:]```, which makes a copy

Omitting a the first index defaults to the beginning (0), and leaving the second index blank defaults to the length of whatever is being sliced.

In a 2D array, since there's rows and columns, there are 2 slice operators, the first of which will take a start index for the row and an end index, while the second one will take a start index for the column and an end index: ```[row start:row end, column start:column end]```.

Again, indexing begins at 0.

In [49]:
A[1, :] # this will return the 2nd row of the matrix, along with all it's column elements from 0 to 3

array([ -5,   2,  -3, -18])

In [50]:
A[:, 2] # this will return the 3rd column of the matrix, along with all it's row elements from 0 to 3

array([ 4, -3, -2])

This is how you get the 2x3 matrix at the bottom right hand corner of A.

In [56]:
A[1:, 1:] #all the columns from columns 1 and onwards, and same with row 1 and onwards

array([[  2,  -3, -18],
       [ 14,  -2,   7]])

**Exercise:** What if you wanted the 3x3 matrix at the left of A (everything but the rightmost column)? Uncomment the code below (click in the box so you have a flashing cursor, and delete the #), erase the underscore blanks, and fill in the correct numbers.

In [62]:
# A[_:_, _:_]

Negative indexing can also be performed in Numpy. This is useful when you don't have the length of the array, and want something starting from the end. The last element has an index of -1, second to last element has an index of -2, and so forth. The same operations from above can be used.

Here's an example with a 1D array.

In [58]:
D = np.arange(1, 10)  #arange is similar to range(), it takes a starting number, end, and a step interval
D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
D[-3]

7

In [60]:
D[2:-3] #remember, the index stops 1 before the last, so the last element is at index -4

array([3, 4, 5, 6])

**Exercise:** Let's try to select the 2x2 matrix at the bottom righthand corner of the A matrix from the last exercise, but this time filling in the blanks with negative indices.

Like before, leaving the 2nd argument blank in both slices below tells it to run all the way to the end.

In [63]:
# A[_:, _:]

This is how you'd do it with positive indices.

In [18]:
A[1:, 2:]

array([[ -3, -18],
       [ -2,   7]])

The shape function returns the dimensions of an array, which can be useful to tell how many elements there are.

In [19]:
A.shape

(3, 4)

The ```reshape``` function, when called on an array, can change it's elements into a new array shape of size (x, y). The number of elements in each array must be equal.

Observe that it fills the array row by row by going along the rows of the original matrix.

In [64]:
A.reshape((6, 2))

array([[ -6,  -9],
       [  4,  -5],
       [ -5,   2],
       [ -3, -18],
       [-14,  14],
       [ -2,   7]])

In [21]:
A.reshape((2, 6))

array([[ -6,  -9,   4,  -5,  -5,   2],
       [ -3, -18, -14,  14,  -2,   7]])

## Broadcasting

The most important thing NumPy does is **broadcasting**, which means that it allows for arithmetic operations on arrays of different shapes.

Broadcasting is when a smaller array is "repeated" across a larger array so they have compatible shapes, and arithmetic can be done between them.

More information can be found here: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html

Here's an example of array multiplication, where both arrays' sizes are equal.

In [22]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

And here broadcasting is being used; the scalar ```b``` is being "stretched" into an array with the same shape as ```a```.

In [23]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

This may seem trivial, but it's important because because uses less memory and is more computationally efficient. This is because in the 2nd example, broadcasting allows less memory to be moved around during the multiplication since b is a scalar rather than an array)

The rule of thumb is that NumPy does arithmetic operations pairwise, but if a certain dimension is 1, then it will **broadcast** that effect across the dimension. Here's a more complicated example.

In [24]:
a = np.array([1.0, 2.0, 3.0])

B = np.zeros((3, 3)) # the zeros function creates an n x n array of all zeros

a + B

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [25]:
a = np.array([[1.0], [2.0], [3.0]]) #now a is a column vector

B = np.zeros((3, 3))

a + B

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [26]:
1 + B #here 1 is being "stretched"

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

What if we want to add a constant vector to each row of a matrix? In the following example, the sizes of the arrays are different, so the sum is performed elementwise.

In [27]:
an_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_vector = np.array([1, 0, 1])
c = an_array + row_vector #the row vector [1, 0, 1] is added to each row of a
c

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

You can also change the axes orientation when you sum up matrices. This will sum along the specified axis; axis=0 is column wise, and axis=1 is row wise.

For example if A is a 2x2 matrix and you sum with axis = 0, it will sum the columns vertically, and with axis = 1, it will sum the rows horizontally.

In [28]:
A = [[1, 3], [4, 5]] #remember, this looks like [1, 3]
np.sum(A, axis=0)    #                          [4, 5]

array([5, 8])

Now try summing with axis = 1.

In [29]:
np.sum(A, axis=1)

array([4, 9])

**Exercise:** Let's try an example with another 2D matrix. Uncomment A (again by deleting the #) and erase the underscore blanks, filling in numbers to make the output equal to ```[3, 12, 8]```.

In [70]:
# A = [[2, _, 5], [_, 9, _]]

In [71]:
np.sum(A, axis=0) #test your values by running this and seeing if it equals an array of [3, 12, 8]

array([ 3, 12,  8])

# Linear Algebra

NumPy also supports many linear algebra operations.

Vectors are single dimensional matrices, and a matrix is multidimensional. Both can be created with brackets, as shown below.

In [91]:
a_vector = [[3], [1], [3]] #this is a column vector
a_vector

[[3], [1], [3]]

In [33]:
a_matrix = [[1, 2, 3], [3, 1, 2], [2, 1, 3]] #this is a 3x3 matrix
a_matrix

[[1, 2, 3], [3, 1, 2], [2, 1, 3]]

Let's practice working with matrices.

In [40]:
A = 10 * np.random.rand(3, 3) #this creates a random 3x3 vector, and makes it bigger
A = A.astype(int) #makes all the elements integers
A

array([[4, 6, 7],
       [4, 7, 8],
       [0, 2, 9]])

With matrices in numpy, you can easily transpose with ```T```.

In [41]:
A.T

array([[4, 4, 0],
       [6, 7, 2],
       [7, 8, 9]])

Another cool thing we can do with numpy matrices is multiplication with the ```@``` operator. This is a main advantage of matrices over vectors. Let's create a vector with 3 elements each with value 1, and then multiply it with ```A```.

In [42]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [43]:
A @ ones #@ is a quick way of multiplying with array matrices

array([17., 19., 11.])

If you haven't taken linear algebra yet, don't worry, matrix multiplication is just multiplying a bunch of numbers and adding them up, as shown below.

![Example of matrix vector multiplication](mult.png)

In [44]:
A * ones # does not work as expected! see the broadcasting section

array([[4., 6., 7.],
       [4., 7., 8.],
       [0., 2., 9.]])

Let's say we want to solve a matrix equation, $Ax = b$, where ```A``` and ```b``` are as follows:

In [45]:
A = [[2, 3, -2], [1, 0, -4], [2, -1, -6]]
b = [[8], [1], [4]]

To find $x$, you multiply both side by the inverse of $A$; the left side simplifies to the 3x3 identity matrix. In Numpy, the inverse can be easily found with ```np.linalg.inv```.

In [40]:
A_inverse = np.linalg.inv(A)
A_inverse

array([[ 0.33333333, -1.66666667,  1.        ],
       [ 0.16666667,  0.66666667, -0.5       ],
       [ 0.08333333, -0.66666667,  0.25      ]])

Now we have to multiply $A$ and $b$. Remember the ```@``` operator?

In [41]:
x = A_inverse @ b
x

array([[5.],
       [0.],
       [1.]])

You could also do it in 1 line, with either of the following:

In [42]:
np.dot(np.linalg.inv(A), b) #np.linalg.inv(A) @ b would also work

array([[5.],
       [0.],
       [1.]])

In [43]:
np.linalg.solve(A, b) #we didn't tell you this, but np.linalg.solve solves a linear matrix equation of the form Ax=B

array([[ 5.],
       [-0.],
       [ 1.]])

## Other Operations

In [44]:
a = np.random.rand(100) #randomly creating 100 numbers from the standard normal distribution

In [45]:
a.mean() #finds the mean of an array of numbers

0.5508743887340501

In [46]:
a.sum() #finds the sum of an array of numbers

55.08743887340502

In [47]:
np.median(a) #finds the median of an array of numbers

0.5410218071856663

## Conditions

Now we're going to see how we can select certain elements based on conditions that we specify. Sometimes you don't want all the rows and columns from a matrix you're given. Let's say we're given the following array.

In [73]:
A = np.arange(2, 20, 3)  #arange is similar to range(), it takes a starting number, end, and a step interval
A

array([ 2,  5,  8, 11, 14, 17])

What if we want every other element in A? We can use boolean (True/False) values to select items that we want. A true values indicates "yes, keep", while a false indicates "no, we don't want this".

In [74]:
A[[True, False, True, False, True, False]]

array([ 2,  8, 14])

But wait, these are just the even numbers. The equality operator ```==``` returns true if the 2 values being compared are equal, and false if they aren't.

In the cell below, the modulo operator gives the remainder when x is divided by y. This is a neat way to test if a number is even or odd.

In [76]:
A[A % 2 == 0] #the stuff in the brackets returns the same boolean array as in the cell above

array([ 2,  8, 14])

Let's try an example on our own. The code below randomly generates a 3x3 matrix.

In [77]:
random_matrix = np.random.rand(3, 3) 
random_matrix

array([[0.38321913, 0.75519805, 0.37120387],
       [0.49226357, 0.89298709, 0.92634108],
       [0.2786668 , 0.59181006, 0.4994011 ]])

**Exercise** What if we only want the numbers that are less than the mean of all the elements of the matrix? Uncomment out the following (erase the #) and fill in the blank between the brackets.

In [52]:
#random_matrix[_____]

## Exercises

### Broadcasting

**Exercise:** Uncomment the x and fill in the 2 blanks so that x + y = z.

In [84]:
# x = np.array([_, _])
y = np.array([[3], [4]])
z = np.array([[4, 5], [5, 6]])
#Hint: y looks like [3] and z looks like [4, 5]
#                   [4]                  [5, 6]
#The row vector will be "stretched" across and added to both elements of the column vector y.

In [85]:
x + y

array([[[ 7,  8],
        [ 9, 10]],

       [[ 7,  8],
        [ 9, 10]]])

### Linear Algebra

In [86]:
x = np.arange(1000).reshape(1000, 1)
b = np.ones((1000, 1))

X = np.append(x, b, axis=1)
#all you need to know is that this is the X you will use in the equation below

Y = 2 * x[:,0] + 4*b + np.random.random()
#all you need to know is that this is the Y you will use in the equation below

Use Least Squares Linear Regression to solve for $\hat{\theta}$, the weights on each column of $X$ such that it models $Y$. Remember, the formula for Least Squares Linear Regression is: 

$$X^TX\hat{\theta} = X^TY$$

In [89]:
# theta_hat = np.linalg.solve(___, ___)
theta_hat

array([[ 3.35779628e-17,  1.67889814e-17, -4.89678625e-17, ...,
         1.79082468e-15,  2.14898962e-15,  2.86531950e-15],
       [ 4.00026737e+00,  6.00026737e+00,  8.00026737e+00, ...,
         1.99800027e+03,  2.00000027e+03,  2.00200027e+03]])

Find the loss of your model. Loss is the difference between estimated and true values for some data; don't worry too much about what it is, we're just using it as an example here.

The loss equation is as follows
$$ ||Y - X\hat{\theta}|| $$
_Hint: First use np.linalg.norm on the difference of Y and the product of X and theta hat, then square._

In [90]:
#loss
loss

5.352182377604267e-18

## Final Notes on Numpy

Numpy makes scientific computing in Python possible. It's pretty fantastic. But there are many tiny details that might trip you up when using it in a practical setting. Sometimes it will have to with using functions properly, othertimes it will be low-level messups.

For a common one that often gets me annoyed, see <a href="http://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html">this link</a>.

Also, remember that whenever you're confused with or forget what parameters a numpy function takes, say with ```np.arange```, you can call ```help(np.arange) ``` in an empty cell.

# Pandas

Pandas is a commonly used data processing library. 

Data is stored in **DataFrame** objects, which is a collection of **Series** objects, which represent columns.

We'll go over an example EDA (exploratory data analysis) and feature engineering process on some data in Pandas.

In [35]:
titanic_train = pd.read_csv('data/titanic/train.csv')
titanic_test = pd.read_csv('data/titanic/test.csv')

First, let's look at the data itself.

In [36]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

Next, let's do some data cleaning. Are there any missing values?

In [1]:
titanic_train.isnull().sum()

NameError: name 'titanic_train' is not defined

The first column with missing values is **Age**. One way we can deal with missing *quantitative* data is **imputing** the missing values with the mean of the column.

We use the <a href=https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.fillna.html>**.fillna**</a> function of Pandas to do this.

In [38]:
titanic_train['Age'] = titanic_train['Age'].fillna(titanic_train['Age'].mean())

The next column with missing values is **Cabin**. In general, the **Cabin** column is weird, so let's investigate it further. We use the <a href=https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.unique.html>.unique</a> to look at the different values of the column.

In [39]:
titanic_train['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6', 'C23 C25 C27',
       'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33', 'F G73', 'E31',
       'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101', 'F E69', 'D47',
       'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4', 'A32', 'B4',
       'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35', 'C87', 'B77',
       'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19', 'B49', 'D',
       'C22 C26', 'C106', 'C65', 'E36', 'C54', 'B57 B59 B63 B66', 'C7',
       'E34', 'C32', 'B18', 'C124', 'C91', 'E40', 'T', 'C128', 'D37',
       'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44', 'A34', 'C104', 'C111',
       'C92', 'E38', 'D21', 'E12', 'E63', 'A14', 'B37', 'C30', 'D20',
       'B79', 'E25', 'D46', 'B73', 'C95', 'B38', 'B39', 'B22', 'C86',
       'C70', 'A16', 'C101', 'C68', 'A10', 'E68', 'B41', 'A20', 'D19',
       'D50', 'D9', 'A23', 'B50', 'A26', 'D48', 'E58', 'C126', 'B71',
       'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63', 'C62 C64', 'E24',

We can also look at the counts of each value in the column.

In [40]:
titanic_train['Cabin'].value_counts().head()

B96 B98        4
G6             4
C23 C25 C27    4
F2             3
C22 C26        3
Name: Cabin, dtype: int64

Seems like each entry has maybe a Floor and a room number: however, some entries seem to have multiple cabins, and some entries are even more interesting: "T", "F E69". There are many ways to approach this data, but for now, let's just take the Floor letter from each cabin and place it into a new column.

Note: this may not be the best way to use the Cabin column: if the goal is to predict if a person survived, it may be important to save not just the floor but also the cabin number---i.e. if different people stay in the same room, maybe they all survived or all died.

In [41]:
titanic_train['Floor'] = titanic_train['Cabin'].apply(lambda cabin: cabin[0] if type(cabin) != float else cabin)

In [42]:
titanic_train['Floor'].value_counts()

C    59
B    47
D    33
E    32
A    15
F    13
G     4
T     1
Name: Floor, dtype: int64

In [43]:
titanic_train['Floor'].unique()

array([nan, 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

Let's also take a look at the types of data in some of the rest of the columns.

In [44]:
titanic_train['Sex'].unique()

array(['male', 'female'], dtype=object)

In [45]:
titanic_train['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [46]:
titanic_train['Pclass'].unique()

array([3, 1, 2])

In [47]:
titanic_train['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [48]:
titanic_train['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

## Dropping Columns, Inplace

Above, when we said:

In [49]:
titanic_train['Age'] = titanic_train['Age'].fillna(titanic_train['Age'].mean())

We had to set it equal to the column after we called **.fillna**: this is because almost all Pandas functions are **non-destructive** by default---if you're performing an operation on the column, Pandas will create a new column, rather than replace an old column.

For example, the <a href=https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html>**.drop**</a> method will not remove a column from a DataFrame, it will create a copy of the DataFrame without that column:

In [50]:
titanic_train['dummy'] = 1
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked Floor  dummy  
0      0         A/5 21171   7.2500   NaN        S   NaN      1  
1      0          PC 17599  71.2833   C85        C     C      1  
2      0  STON/O2. 3101282   7.9250   NaN        S   NaN      1  
3      0            113803  53.1000  C123        S     C      1  
4      0            373450   8.0500   NaN        S   NaN      1

In [51]:
titanic_train.drop('dummy', axis=1).head() # axis = 1 means drop columns, not rows: if you wanted to drop rows, pass in the row index

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked Floor  
0      0         A/5 21171   7.2500   NaN        S   NaN  
1      0          PC 17599  71.2833   C85        C     C  
2      0  STON/O2. 3101282   7.9250   NaN        S   NaN  
3      0            113803  53.1000  C123        S     C  
4      0            373450   8.0500   NaN        S   NaN

However, if we pass in **inplace=True**, then Pandas will delete the column in the original DataFrame: many other functions in Pandas have this functionality.

In [52]:
titanic_train['dummy'] = 1
titanic_train.drop('dummy', inplace=True, axis=1)
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked Floor  
0      0         A/5 21171   7.2500   NaN        S   NaN  
1      0          PC 17599  71.2833   C85        C     C  
2      0  STON/O2. 3101282   7.9250   NaN        S   NaN  
3      0            113803  53.1000  C123        S     C  
4      0            373450   8.0500   NaN        S   NaN

Be warned: doing things inplace is dangerous! Say, for example, it took a really long time to load in your database (maybe you had to do some web scraping, or you downloaded it directly from a URL and you lost Internet connection). If you do **drop** operations inplace, without saving the original state of the DataFrame, you could lose data.

In general, it is usually a good idea to save your DataFrame in states throughout your EDA.

## One-hot encoding

A lot of the Titanic data is **categorical**: one way to deal with this kind of data so that we can do predictive modeling is **one-hot encoding**, which means we transform a column, "Pclass" for example, which has 3 different values into 3 different columns with 0 or 1 values, e.g. the values are 1, 2, 3, so 2 turns into [0 1 0].

We use the <a href=https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html>**get_dummies**</a> function in Pandas.

Let's do this for some of the columns in the data.

In [53]:
titanic_train_copy = titanic_train.copy() # save the state of your DF

def one_hot(df, columns):
    for column in columns:
        # this means one-hot encode the column, and make the column title Pclass_{value}, for example
        col_onehot = pd.get_dummies(df[column], prefix=column) 
        df.drop(column, axis=1, inplace=True)
        df = df.join(col_onehot)
    return df

titanic_train_one_hot = one_hot(titanic_train_copy, ['Pclass', 'Sex', 'SibSp', 'Parch'])

In [54]:
titanic_train_one_hot.head()

PassengerId  Survived                                               Name  \
0            1         0                            Braund, Mr. Owen Harris   
1            2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3         1                             Heikkinen, Miss. Laina   
3            4         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5         0                           Allen, Mr. William Henry   

    Age            Ticket     Fare Cabin Embarked Floor  Pclass_1   ...     \
0  22.0         A/5 21171   7.2500   NaN        S   NaN         0   ...      
1  38.0          PC 17599  71.2833   C85        C     C         1   ...      
2  26.0  STON/O2. 3101282   7.9250   NaN        S   NaN         0   ...      
3  35.0            113803  53.1000  C123        S     C         1   ...      
4  35.0            373450   8.0500   NaN        S   NaN         0   ...      

   SibSp_4  SibSp_5  SibSp_8  Parch_0  Parch_1  Parch_2  Parch_3  Parch_4  \
0        0        0        0        1        0        0        0        0   
1        0        0        0        1        0        0        0        0   
2        0        0        0        1        0        0        0        0   
3        0        0        0        1        0        0        0        0   
4        0        0        0        1        0        0        0        0   

   Parch_5  Parch_6  
0        0        0  
1        0        0  
2        0        0  
3        0        0  
4        0        0  

[5 rows x 28 columns]

NOTE: The .get_dummies function will do nothing with missing values, so when one-hot encoding columns with missing values, create a dummy value for these missing values, so it will turn into a category that .get_dummies will create a column for.

In [55]:
titanic_train['Floor'] = titanic_train['Floor'].fillna('null')
pd.get_dummies(titanic_train['Floor'], prefix='Floor').head()

Floor_A  Floor_B  Floor_C  Floor_D  Floor_E  Floor_F  Floor_G  Floor_T  \
0        0        0        0        0        0        0        0        0   
1        0        0        1        0        0        0        0        0   
2        0        0        0        0        0        0        0        0   
3        0        0        1        0        0        0        0        0   
4        0        0        0        0        0        0        0        0   

   Floor_null  
0           1  
1           0  
2           1  
3           0  
4           1

### Exercise

Clean the rest of the columns of the Titanic data set and use <a href=http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html>sklearn.LogisticRegression</a> to create a model for the 'Survived' column.